version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: magazine_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - magazine_network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: magazine_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - magazine_network

  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: magazine_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - magazine_network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: magazine_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - magazine_network

  # AI Service
  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: magazine_ai
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./ai_service:/app
    environment:
      - SERPAPI_KEY=${SERPAPI_KEY}
      - WORLDNEWS_API_KEY=${WORLDNEWS_API_KEY}
      - CURRENTS_API_KEY=${CURRENTS_API_KEY}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - MODEL_NAME=${MODEL_NAME}
    networks:
      - magazine_network

  # Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: magazine_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - magazine_network

networks:
  magazine_network:
    driver: bridge

volumes:
  mysql_data:
  ollama_data: 