version: '3.8'

services:
  # Backend Laravel Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: magazine-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=aimagazinedb
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - magazine_network

  # Database Service
  db:
    image: mariadb:10.6
    restart: always
    container_name: magazine-db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=aimagazinedb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - magazine_network

  # Scraper Service
  scraper:
    build:
      context: ./ai_service/scraper
      dockerfile: Dockerfile
    container_name: magazine-scraper
    restart: always
    volumes:
      - ./ai_service/scraper:/app
      - scraper_output:/app/output
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=aimagazinedb
      - DB_USER=root
      - DB_PASSWORD=root_password
      - BACKEND_API_URL=http://backend/api/articles
      - ARTICLES_BATCH_API_URL=http://backend/api/articles/batch
      - ARTICLES_IMPORT_API_URL=http://backend/api/articles/import
      - CATEGORIES_API_URL=http://backend/api/categories
    depends_on:
      - db
      - backend
    networks:
      - magazine_network

  # Rewrite Service
  rewrite:
    build:
      context: ./ai_service/rewrite
      dockerfile: Dockerfile
    container_name: magazine-rewrite
    restart: always
    volumes:
      - ./ai_service/rewrite:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=aimagazinedb
      - DB_USER=root
      - DB_PASSWORD=root_password
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=gemma2
    depends_on:
      - db
      - ollama
    networks:
      - magazine_network

  # Keyword Rewrite Service (always running)
  keyword_rewrite:
    build:
      context: ./ai_service/keyword_rewrite
      dockerfile: Dockerfile
    container_name: magazine-keyword-rewrite
    restart: always
    volumes:
      - ./ai_service/keyword_rewrite:/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=False
      - OLLAMA_MODEL=gemma2:latest
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - magazine_network

  # Ollama Service (for AI models)
  ollama:
    image: ollama/ollama:latest
    container_name: magazine-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - magazine_network

  # Scheduler Service
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: magazine-scheduler
    restart: always
    depends_on:
      - scraper
      - rewrite
      - keyword_rewrite
    networks:
      - magazine_network

networks:
  magazine_network:
    driver: bridge

volumes:
  db_data:
  ollama_data:
  scraper_output: 